# Generated by Django 5.1.3 on 2025-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'permissions': [('can_view_blocked', 'Может просматривать заблокированные карты')], 'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AddField(
            model_name='field',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокировано'),
        ),
        migrations.AddField(
            model_name='fieldreport',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Жалоба одобрена'), ('rejected', 'Жалоба отклонена')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокировано'),
        ),
    ]
