# Generated by Django 5.2.1 on 2025-05-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_comment_options_alter_field_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='reason',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
