# Generated by Django 5.1.6 on 2025-03-28 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='field',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_fields', to=settings.AUTH_USER_MODEL),
        ),
    ]
