# Generated by Django 5.1.6 on 2025-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_field_favorites_field_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='coordinates',
            field=models.JSONField(blank=True, default=dict, help_text="Координаты в формате {'lat': 55.7558, 'lng': 37.6173}", null=True),
        ),
    ]
