# Generated by Django 5.1.3 on 2025-03-30 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='field',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='field',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
