# Generated by Django 5.1.6 on 2025-04-03 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_comment_options_rename_user_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reported_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
