# Generated by Django 5.1.6 on 2025-04-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_comment_options_rename_user_comment_author_and_more'),
        ('main_app', '0007_fieldreport_delete_reportfield'),
    ]

    operations = [
    ]
