# Generated by Django 5.1.6 on 2025-04-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_comment_likes_comment_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='cols',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='field',
            name='rows',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='main_app.field')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='main_app.field')),
            ],
            options={
                'unique_together': {('field', 'x', 'y')},
            },
        ),
    ]
