# Generated by Django 5.2 on 2025-04-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_comment_options_alter_field_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'permissions': [('can_view_blocked', 'Может просматривать заблокированные карты')], 'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
    ]
