# Generated by Django 5.1.3 on 2025-04-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20250412_1709'),
        ('main_app', '0013_fieldfile_field_file'),
    ]

    operations = [
    ]
