# Generated by Django 5.1.6 on 2025-04-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20250413_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
